package seleniumtests;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterGroups;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeGroups;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import framework.Base;

import org.openqa.selenium.Keys;

public class GoogleSearchTest extends Base {

	@Test(description = "to verify google search for keyword 'Selenium Dev'", priority = 1, groups = "GROUP_1") // testng
																												// test
																												// case
	// annotation
	public void googleSearchTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("selenium dev", Keys.ENTER);
		String title = driver.getTitle();
		Reporter.log("search result title for Selenium dev: " + title, true);
	}

	@Test(description = "to verify google search for keyword 'testng.org'", priority = 2) // testng test case annotation
	public void googleSearchTestNGTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("testng.org", Keys.ENTER);
		String title = driver.getTitle();
		Reporter.log("search result title for testng.org: " + title, true);
	}

	@Test(description = "to verify google search for keyword 'Java OOPS'", priority = 3) // testng test case annotation
	public void googleSearchJavaOOPSTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("Java OOPS", Keys.ENTER);
		String title = driver.getTitle();
		Reporter.log("search result title: " + title, true);

	}

}
