package seleniumtests;

import java.util.Set;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;
import org.openqa.selenium.Keys;

public class SeleniumRecapTest {
	@Test // testng test case annotation
	public static void googleSearchTest() throws InterruptedException {

		WebDriver driver;
		System.setProperty("webdriver.chrome.driver",
				"D:\\sqa-guru\\bat-may22-6-7pm\\batch-may-2022-7pm-ws\\automation-testing-batch-may-2022-7pm\\resources\\drivers\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("https://www.google.com/");
		Thread.sleep(2000);
		driver.manage().window().maximize();// maximize the browser
		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("selenium dev", Keys.ENTER);
		String title = driver.getTitle();
		System.out.println("search result title: " + title);
		driver.navigate().back();// navigate back on the browser
		Thread.sleep(1000);
		driver.navigate().forward();
		Thread.sleep(1000);
		driver.navigate().refresh();// reloads the page
		String searchResultURL = driver.getCurrentUrl();
		System.out.println("searchResultURL: " + searchResultURL);

		// driver.wait(1000);
		System.out.println("performed wait");

		Set<Cookie> cookies = driver.manage().getCookies();
		System.out.println("cookies size: " + cookies.size());
		for (Cookie cookie : cookies) {
			System.out.println(cookie.getName() + " : " + cookie.getValue());
		}

		driver.quit();

	}
}
