package seleniumtests;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import framework.Base;

import org.openqa.selenium.Keys;

public class TestNGDependencyTest extends Base{

	@Test(description = "to verify google search for keyword 'Selenium Dev'", groups = "GROUP_1") // testng test case
	// annotation
	public void googleSearchTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("selenium dev", Keys.ENTER);
		String title = driver.getTitle();
		Assert.assertEquals(title, "selenium dev", "Verify google search result page title");
		Reporter.log("search result title for Selenium dev: " + title, true);
	}

	@Test(description = "to verify google search for keyword 'testng.org'", dependsOnMethods = "googleSearchTest") // testng
																													// annotation
	public void googleSearchTestNGTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("testng.org", Keys.ENTER);
		String title = driver.getTitle();
		Reporter.log("search result title for testng.org: " + title, true);
	}

	@Test(description = "to verify google search for keyword 'Java OOPS'", dependsOnMethods = "googleSearchTest", alwaysRun = true) // testng
	// annotation
	public void googleSearchJavaOOPSTest() throws InterruptedException {

		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("Java OOPS", Keys.ENTER);
		String title = driver.getTitle();
		Reporter.log("search result title: " + title, true);

	}

}
